name:                verified-avl
version:             0.1.0.0
github:              "github.com/oisdk/verified-avl"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/verified-avl#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Wpartial-fields
- -Wcompat

default-extensions:
- DataKinds
- KindSignatures
- GADTs
- RankNTypes
- ScopedTypeVariables
- LambdaCase
- StandaloneDeriving
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable

library:
  source-dirs: src

tests:
  verified-avl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - verified-avl
